// <auto-generated />
using System;
using EmployeeAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230114095127_Initial_Commit")]
    partial class Initial_Commit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeAPI.Entities.Qualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Qualifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alias = "SLC",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2023, 1, 14, 9, 51, 26, 812, DateTimeKind.Utc).AddTicks(7863),
                            IsDeleted = false,
                            Name = "School Leaving Certificate",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 2,
                            Alias = "10 +2",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2023, 1, 14, 9, 51, 26, 812, DateTimeKind.Utc).AddTicks(8515),
                            IsDeleted = false,
                            Name = "Higher Secondary School",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 3,
                            Alias = "Bachelor",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2023, 1, 14, 9, 51, 26, 812, DateTimeKind.Utc).AddTicks(8535),
                            IsDeleted = false,
                            Name = "Bachelor",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 4,
                            Alias = "Master",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2023, 1, 14, 9, 51, 26, 812, DateTimeKind.Utc).AddTicks(8537),
                            IsDeleted = false,
                            Name = "Master",
                            UpdatedBy = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
